apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codefresh-delivery-pipelines
spec:
  rules:
    - http:
        paths:
          - path: /webhooks/yarik
            backend:
              service:
                name: yarik-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/eti
            backend:
              service:
                name: eti-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/eti2
            backend:
              service:
                name: eti2-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/eti3
            backend:
              service:
                name: eti3-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/eti123
            backend:
              service:
                name: eti123-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/nima
            backend:
              service:
                name: nima-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
