apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codefresh-delivery-pipelines
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /webhooks/test
            backend:
              service:
                name: test-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
          - path: /webhooks/test2
            backend:
              service:
                name: test2-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
