apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codefresh-delivery-pipelines
spec:
  rules:
    - http:
        paths:
          - path: /webhooks/demo
            backend:
              service:
                name: demo-eventsource-svc
                port:
                  number: 80
            pathType: ImplementationSpecific
