apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-65255964-3fc6-41fc-93ba-14e81784004a:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo2/github-65255964-3fc6-41fc-93ba-14e81784004a
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
