apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-db0d04d6-7208-4387-88ec-130f5e903eb0:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo/github-db0d04d6-7208-4387-88ec-130f5e903eb0
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
