apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo3
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-59caaa51-d10a-4edd-8921-49df2a348f3f:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/demo3/github-59caaa51-d10a-4edd-8921-49df2a348f3f
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
