apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-db0d04d6-7208-4387-88ec-130f5e903eb0
      eventName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
      eventSourceName: demo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-db0d04d6-7208-4387-88ec-130f5e903eb0
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: https://github.com/codefresh-io/cli
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: quay.io/eti_zaguri/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: 1.7.1
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }} '
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: '{{ .Input.body.head_commit.url }} '
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-db0d04d6-7208-4387-88ec-130f5e903eb0
                dataTemplate: '{{ .Input.body.head_commit.message }} '
