apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eti
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/eti/github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
