apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: eti
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
      eventName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
      eventSourceName: eti
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: eti-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
                dataTemplate: https://github.com/codefresh-io/cli
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
                dataTemplate: quay.io/eti_zaguri/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
                dataTemplate: 1.9.0
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
                dataTemplate: '{{ .Input.body.head_commit.url }} '
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-42ad9e6c-ec2f-408e-9c2c-3f23c27a7dbb
                dataTemplate: '{{ .Input.body.head_commit.message }} '
