apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: eti123
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-1a1d049e-b318-4dd4-b67c-2ab408d62035
      eventName: github-1a1d049e-b318-4dd4-b67c-2ab408d62035
      eventSourceName: eti123
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-1a1d049e-b318-4dd4-b67c-2ab408d62035
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: eti123-push-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: https://github.com/codefresh-io/cli
                    - name: IMAGE_NAME
                      value: 'quay.io/eti_zaguri/test'
#                     - name: IMAGE_TAG
#                       value: ''
                    - name: GIT_REVISION
                      value: master
#                     - name: GIT_BRANCH
#                       value: ''
#                     - name: GIT_COMMIT_URL
#                       value: ''
#                     - name: GIT_COMMIT_MESSAGE
#                       value: ''
#                     - name: DOCKERFILE
#                       value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: docker-registry
                workflowTemplateRef:
                  name: ci-simple
          parameters: []
