apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eti3
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/eti3/github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
