apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: eti3
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
      eventName: github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
      eventSourceName: eti3
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: eti3-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
                dataTemplate: repo
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-cc5eece8-c15e-44d0-8d0b-ad70f8df9612
                dataTemplate: image
