apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: nima
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
