apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test4
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-a4c291ae-6685-47c8-9774-b91fd74959ea:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test4/github-a4c291ae-6685-47c8-9774-b91fd74959ea
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
