apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test2
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-5341f5ab-e334-4c66-89eb-15daf35f93ff
      eventName: github-5341f5ab-e334-4c66-89eb-15daf35f93ff
      eventSourceName: test2
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-5341f5ab-e334-4c66-89eb-15daf35f93ff
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test2-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-5341f5ab-e334-4c66-89eb-15daf35f93ff
                dataTemplate: '1'
