apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-a63bd294-913a-4dac-85d7-74a1903827af:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test/github-a63bd294-913a-4dac-85d7-74a1903827af
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
