apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-5341f5ab-e334-4c66-89eb-15daf35f93ff:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test2/github-5341f5ab-e334-4c66-89eb-15daf35f93ff
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
