apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
      eventName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
      eventSourceName: test
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: https://github.com/codefresh-io/cli/
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: quay.io/eti_zaguri/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: 1.5.6
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: master
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: main
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: '{{ .Input.body.head_commit.url }} '
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
                dataTemplate: '{{ .Input.body.head_commit.message }} '
