apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test4
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-c1bee83c-7296-4a9c-9823-0710b0a2f9ec:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test4/github-c1bee83c-7296-4a9c-9823-0710b0a2f9ec
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
