apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test3
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-6f8d5c2d-a199-4e32-a461-2ead71aa7714:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test3/github-6f8d5c2d-a199-4e32-a461-2ead71aa7714
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
