apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test2
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-d7f9aa54-61d9-46d4-8cc9-421743363f21:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/github/github-d7f9aa54-61d9-46d4-8cc9-421743363f21
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
