apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test3
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-6f8d5c2d-a199-4e32-a461-2ead71aa7714
      eventName: github-6f8d5c2d-a199-4e32-a461-2ead71aa7714
      eventSourceName: test3
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: push
        conditions: github-6f8d5c2d-a199-4e32-a461-2ead71aa7714
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: test3-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters: []
