apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - demo-runtime_git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/test/github-27cf3ea2-30ba-4828-8d14-9cba2b0f7c5f
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
