apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: yarik
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-21a46351-4033-4d14-b8a6-01810c8fd952:
      events:
        - push
      repositories:
        - owner: eti-codefresh
          names:
            - pipeline-flow-demo
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/yarik/github-21a46351-4033-4d14-b8a6-01810c8fd952
        url: https://eti.pipeline-team.cf-cd.com
      active: true
      insecure: false
      contentType: json
      apiToken:
        name: autopilot-secret
        key: git_token
