apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: yarik
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-21a46351-4033-4d14-b8a6-01810c8fd952
      eventName: github-21a46351-4033-4d14-b8a6-01810c8fd952
      eventSourceName: yarik
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: push
        conditions: github-21a46351-4033-4d14-b8a6-01810c8fd952
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: yarik-push-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: https://github.com/codefresh-io/cli
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: quay.io/eti_zaguri/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: 1.8.0
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }} '
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: '{{ .Input.body.head_commit.url }} '
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-21a46351-4033-4d14-b8a6-01810c8fd952
                dataTemplate: '{{ .Input.body.head_commit.message }} '
